# Generated by Django 4.0.5 on 2022-06-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=200)),
                ('image_author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_author_link', models.CharField(blank=True, max_length=250, null=True)),
                ('image_website_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image_website_link', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
